export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const STAFF_SEARCH_START = 'STAFF_SEARCH_START';
export const STAFF_SEARCH_SUCCESS = 'STAFF_SEARCH_SUCCESS';
export const STAFF_SEARCH_FAIL = 'STAFF_SEARCH_FAIL';


export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
